# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

defaultLevel: 4
cost: 10
revive: true
reviveSeconds: 5
reviveAmount: 30
wireRange: 30
